apiVersion: butler.butlerlabs.dev/v1alpha1
kind: MachineRequest
metadata:
  labels:
    app.kubernetes.io/name: butler-api
    app.kubernetes.io/managed-by: kustomize
  name: machinerequest-sample
spec:
  providerRef:
    name: harvester-config
    namespace: default
  machineName: sample-vm
  role: worker
  cpu: 4
  memoryMB: 16384
  diskGB: 100
