apiVersion: butler.butlerlabs.dev/v1alpha1
kind: ProviderConfig
metadata:
  labels:
    app.kubernetes.io/name: butler-api
    app.kubernetes.io/managed-by: kustomize
  name: harvester-config
spec:
  provider: harvester
  credentialsRef:
    name: harvester-kubeconfig
    namespace: default
  harvester:
    namespace: default
    networkName: default/vlan40-workloads
    imageName: default/image-5rs6d
