apiVersion: butler.butlerlabs.dev/v1alpha1
kind: ProviderConfig
metadata:
  labels:
    app.kubernetes.io/name: butler-api
    app.kubernetes.io/managed-by: kustomize
  name: providerconfig-sample
spec:
  # TODO(user): Add fields here
